export default [
    { left: 'Sad Song', right: 'Happy Song' },
    { left: 'Sad Movie', right: 'Happy Movie' },
    { left: 'Rough', right: 'Smooth' },
    { left: 'Slow', right: 'Fast' },
    { left: 'Useless Invention', right: 'Useful Invention' },
    { left: 'Ugly Man', right: 'Handsome Man' },
    { left: 'Ugly Woman', right: 'Pretty Woman' },
    { left: 'Worthless', right: 'Priceless' },
    { left: 'Bad Show', right: 'Good Show' },
    { left: 'Bad Song', right: 'Good Song' },
    { left: 'Bad Movie', right: 'Good Movie' },
    { left: 'Fragile', right: 'Indestructible' },
    { left: 'Low Quality', right: 'High Quality' },
    { left: 'Cold', right: 'Hot' },
    { left: 'Round', right: 'Pointy' },
    { left: 'Inflexible', right: 'Flexible' },
    { left: 'Unhygienic', right: 'Hygienic' },
    { left: 'Taste Bad', right: 'Taste Good' },
    { left: 'Unhealthy', right: 'Healthy' },
    { left: 'Skinny', right: 'Fat' },
    { left: 'Selfish', right: 'Giving' },
    { left: 'Uncool', right: 'Cool' },
    { left: 'Quiet', right: 'Loud' },
    { left: 'Wet', right: 'Dry' },
    { left: 'Close', right: 'Far' },
    { left: 'Boring', right: 'Exciting' },
    { left: 'Hate', right: 'Love' },
    { left: 'Illegal', right: 'Legal' },
    { left: 'Humorless', right: 'Hilarious' },
    { left: 'Little Brain', right: 'Big Brain' },
    { left: 'Villain', right: 'Hero' },
    { left: 'Cold', right: 'Hot' },
    { left: 'Dangerous', right: 'Safe' },
    { left: 'Easy Task', right: 'Hard Task' },
    { left: 'Useless Body Part', right: 'Useful Body Part' },
    { left: 'Light', right: 'Heavy' },
    { left: 'Boring', right: 'Exciting' },
    { left: 'Hairless', right: 'Hairy' },
    { left: 'Unpopular Activity', right: 'Popular Activity' },
    { left: 'Trashy', right: 'Classy' },
    { left: 'Weak', right: 'Strong' },
    { left: 'Disgusting Cereal', right: 'Delicious Cereal' },
    { left: 'Liberal', right: 'Conservative' },
    { left: 'Fad', right: 'Classic' },
    { left: 'For Kids', right: 'For Adults' },
    { left: 'Useless In An Emergency', right: 'Uselful In An Emergency' },
    { left: 'Better Cold', right: 'Better Hot' },
    { left: 'Mass Produced', right: 'Artisanl' },
    { left: 'Stupid', right: 'Brilliant' },
    { left: 'Ineffective', right: 'Effective' },
    { left: 'Bad Superpower', right: 'Good Superpower' },
    { left: 'Worst Living Person', right: 'Greatest Living Person' },
    { left: 'Underrated', right: 'Overrated' },
    { left: 'Messy Food', right: 'Clean Food' },
    { left: 'Unethical', right: 'Ethical' },
    { left: 'Boring Hobby', right: 'Interesting Lobby' },
    { left: 'Unfashionable', right: 'Fashionable' },
    { left: 'Harmless', right: 'Harmful' },
    { left: 'Requires Luck', right: 'Requires Skill' },
    { left: 'Unimportant', right: 'Important' },
    { left: 'Vice', right: 'Virtue' },
    { left: 'Hard To Find', right: 'Easy To Find' },
    { left: 'Unstable', right: 'Stable' },
    { left: 'Temporary', right: 'Permanent' },
    { left: 'Easy To Kill', right: 'Hard To Kill' },
    { left: 'Smells Bad', right: 'Smells Good' },
    { left: 'Low Calorie', right: 'High Calorie' },
    { left: 'Easy Subject', right: 'Hard Subject' },
    { left: 'Bad Actor', right: 'Good Actor' },
    { left: 'Casual', right: 'Formal' },
    { left: 'Underpaid', right: 'Overpaid' },
    { left: 'Forbidden', right: 'Encouraged' },
    { left: 'Bad Habit', right: 'Good Habit' },
    { left: 'Easy To Remember', right: 'Hard To Remember' },
    { left: 'Historically Irrelevant', right: 'Historically Important' },
    { left: 'Normal Pet', right: 'Exotic Pet' },
    { left: 'Book Was Better', right: 'Movie Was Better' },
    { left: 'Bad Pizza Topping', right: 'Good Pizza Topping' },
    { left: 'Mental Activity', right: 'Physical Activity' },
    { left: 'Straight', right: 'Curvy' },
    { left: 'Optional', right: 'Mandatory' },
    { left: 'Unsexy Animal', right: 'Sexy Animal' },
    { left: 'Bad Reputation', right: 'Good Reputation' },
    { left: 'Useless Major', right: 'Useful Major' },
    { left: 'Underrated Movie', right: 'Overratted Movie' },
    { left: 'Scary Animal', right: 'Nice Animal' },
    { left: 'Nobody Does It', right: 'Everyone Does It' },
    { left: 'Small', right: 'Big' }
];