export default [
    { left: 'Sad Song', right: 'Happy Song' },
    { left: 'Sad Movie', right: 'Happy Movie' },
    { left: 'Rough', right: 'Smooth' },
    { left: 'Slow', right: 'Fast' },
    { left: 'Useless Invention', right: 'Useful Invention' },
    { left: 'Ugly Man', right: 'Handsome Man' },
    { left: 'Ugly Woman', right: 'Pretty Woman' },
    { left: 'Worthless', right: 'Priceless' },
    { left: 'Bad Show', right: 'Good Show' },
    { left: 'Bad Song', right: 'Good Song' },
    { left: 'Bad Movie', right: 'Good Movie' },
    { left: 'Fragile', right: 'Indestructible' },
    { left: 'Low Quality', right: 'High Quality' },
    { left: 'Cold', right: 'Hot' },
    { left: 'Round', right: 'Pointy' },
    { left: 'Inflexible', right: 'Flexible' },
    { left: 'Unhygienic', right: 'Hygienic' },
    { left: 'Taste Bad', right: 'Taste Good' },
    { left: 'Sick', right: 'Healthy' },
    { left: 'Skinny', right: 'Fat' },
    { left: 'Uncool', right: 'Cool' },
    { left: 'Quiet', right: 'Loud' },
    { left: 'Wet', right: 'Dry' },
    { left: 'Villain', right: 'Hero' },
    { left: 'Cold', right: 'Hot' },
    { left: 'Dangerous', right: 'Safe' },
    { left: 'Easy Task', right: 'Hard Task' },
    { left: 'Useless Body Part', right: 'Useful Body Part' },
    { left: 'Light', right: 'Heavy' },
    { left: 'Boring', right: 'Exciting' },
    { left: 'Small', right: 'Big' }
];